
steps:
  - id:  Install Dependencies
    name: node:12.16.2
    dir: 'client'
    entrypoint: npm
    args: ['ci']

  - id:  Run Unit Tests
    name: node:12.16.2
    dir: 'client'
    entrypoint: npm
    args: ['test']
