export interface story {
    abstract: any[]
    autoGeneratedSummary: string
    byline: string
    card: string
    contentTags: any[]
    eyebrowSite: string
    id: string
    image: string
    internalID: string
    longURL: string
    primaryCategory: any
    primarySite: string
    published: number
    readings: any[]
    secondaryBrands: any[]
    shortURL: string
    summary: string
    thumbnailImage: string
    title: string
    updatedAt: number
    wordCount: number
}

export interface module {
    stories: story[]
}

export interface newsResponse {
    title: string
    modules: module[]
}

export interface NewsStory {
    date: Date
    headline: string
    link: string
    summary?: string
}